// PINs 
#define LED1 2
#define LED2 4
#define LED3 6
#define LED4 8
#define LED5 10
#define LED_STATUS 11
#define SW 13

// Switch ON/OFF
#define SW_ON 0
#define SW_OFF 1

// Blink LED mode
#define BLINK_INIT 1
#define BLINK_NOT_CASTED 2
#define BLINK_CASTED 3
#define BLINK_TIMER_RESET 4

// morse code rate 
#define MORSE_SHORT_DUR 150
#define MORSE_LONG_DUR MORSE_SHORT_DUR*3
#define MORSE_ADJUSTMENT_DUR 100

#define MORSE_SHORT_MIN MORSE_SHORT_DUR - MORSE_ADJUSTMENT_DUR
#define MORSE_SHORT_MAX MORSE_SHORT_DUR + MORSE_ADJUSTMENT_DUR
#define MORSE_LONG_MIN MORSE_LONG_DUR - MORSE_ADJUSTMENT_DUR
#define MORSE_LONG_MAX MORSE_LONG_DUR + MORSE_ADJUSTMENT_DUR

#define RESET_DUR 3000

